[package]
name = "fatescroll"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
diceman = { git = "https://github.com/snits/diceman.git", subdirectory = "crates/diceman", branch = "main" }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2"

[dev-dependencies]
tempfile = "3"
